spring.application.name=product-catalog-service
# Server Port
server.port=8080

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
# This tells Hibernate to use the PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# This will automatically create/update the database table based on your @Entity class
spring.jpa.hibernate.ddl-auto=update
# Shows the SQL queries in the console for debugging
spring.jpa.show-sql=true