spring.application.name=order-service-simulator
# AWS Region
aws.region=us-east-1

# AWS SQS Queue URL from your initial setup
aws.sqs.queue.order-placement-url=https://sqs.us-east-1.amazonaws.com/841162675860/Jd.fifo
# Server Port
server.port=8083