spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server: # Add this server level
        webflux: # Add this webflux level
          routes:
            - id: product-catalog-service
              uri: lb://PRODUCT-CATALOG-SERVICE
              predicates:
                - Path=/products/**
              filters:
                - RewritePath=/products(?<segment>/?.*), /api/v1/products$\{segment}

            - id: inventory-service
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/inventory/**
              filters:
                - RewritePath=/inventory(?<segment>/?.*), /api/v1/inventory$\{segment}